apiVersion: v1
kind: Service
metadata:
  name: label-service
  namespace: saga-shipping
  labels:
    app: label-service
spec:
  type: ClusterIP
  selector:
    app: label-service
  ports:
  - name: http
    protocol: TCP
    port: 5007
    targetPort: 5007